// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuL_8HyGIudb3LB2Ct0QdwmrWVxdfS-tw',
    appId: '1:365691447823:web:a7cf32b319b1ebc001117a',
    messagingSenderId: '365691447823',
    projectId: 'taylara-d2bbe',
    authDomain: 'taylara-d2bbe.firebaseapp.com',
    storageBucket: 'taylara-d2bbe.firebasestorage.app',
    measurementId: 'G-42V6V3Q4P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKMWmR-y2OEr3rjELiqlWSSZZiFbDmc14',
    appId: '1:365691447823:android:b430ac314c3c1dc501117a',
    messagingSenderId: '365691447823',
    projectId: 'taylara-d2bbe',
    storageBucket: 'taylara-d2bbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-7yTYZfZ8AOjahhVr2KuO4TJORhAjQ4',
    appId: '1:365691447823:ios:6a5ea04d30614f6001117a',
    messagingSenderId: '365691447823',
    projectId: 'taylara-d2bbe',
    storageBucket: 'taylara-d2bbe.firebasestorage.app',
    iosBundleId: 'com.example.modernPlasterCastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-7yTYZfZ8AOjahhVr2KuO4TJORhAjQ4',
    appId: '1:365691447823:ios:6a5ea04d30614f6001117a',
    messagingSenderId: '365691447823',
    projectId: 'taylara-d2bbe',
    storageBucket: 'taylara-d2bbe.firebasestorage.app',
    iosBundleId: 'com.example.modernPlasterCastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuL_8HyGIudb3LB2Ct0QdwmrWVxdfS-tw',
    appId: '1:365691447823:web:3a02a54a6fdab9e901117a',
    messagingSenderId: '365691447823',
    projectId: 'taylara-d2bbe',
    authDomain: 'taylara-d2bbe.firebaseapp.com',
    storageBucket: 'taylara-d2bbe.firebasestorage.app',
    measurementId: 'G-RVS8QSN09R',
  );
}
